[model]
default_model="models/free-style_15x15_619.onnx"
free_style_model="models/free-style_15x15_619.onnx"
renju_model="models/renju_15x15_508.onnx"
standard_model="models/standard_15x15_496.onnx"
caro_model="models/caro_15x15_488.onnx"

[MCTS]
# number of MCTS simulations
num_mct_sims=100
# number of MCTS threads
num_mct_threads=10
