[model]
default_model="free-style_15x15_536.onnx"
free_style_model="free-style_15x15_536.onnx"
renju_model="renju_15x15_503.onnx"
standard_model="standard_15x15_491.onnx"
caro_model="caro_15x15_488.onnx"

[MCTS]
# number of MCTS simulations
num_mct_sims=100
# number of MCTS threads
num_mct_threads=10
