[model]
default_model="models/free-style_15x15_651.onnx"
free_style_model="models/free-style_15x15_651.onnx"
renju_model="models/renju_15x15_514.onnx"
standard_model="models/standard_15x15_500.onnx"
caro_model="models/caro_15x15_497.onnx"
standard_caro_model="models/standard_caro_15x15_488.onnx"

[MCTS]
# number of MCTS simulations
num_mct_sims=100
# number of MCTS threads
num_mct_threads=10
